### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet-admin#36]
Need to be able to do searches for ip numbers, partial emails account names etc

**Comment by gregory-latinier** [comment]
Do we trust the users or do we need to take care of SQL injection and things like that ?

**Comment by jnordberg** [comment]
We should never allow SQL injection :)

**Comment by gregory-latinier** [comment]
Sure but since you want something like that : `SELECT * FROM users WHERE <query>` we can inject what we want 
`<query>: email = 'blabal@email.com; TRUNCATE table;'` 
So how flexible do you want this `query` ?

**Comment by jnordberg** [comment]
If we allow the requests to provide the `where:` option in sequelize wouldn't that be sanitised?

**Comment by gregory-latinier** [comment]
So we would write a JSON format quey rather than pure SQL like suggested

**Comment by jnordberg** [comment]
Yes, that would be one way to do it

**Comment by gregory-latinier** [comment]
The operators aliases are disabled so we can't query with a like operator for example if we use JSON. Sorry I forgot about that.
All the fields you named are strings so I could write query with all string fields separated with an OR and LIKE operator.
We would have something equivalent to
`SELECT * FROM users WHERE username like '%?%' OR ip like '%?%' ...`
Is that OK for you ?

**Comment by Gandalf-the-Grey** [comment]
Some notes about features that might be valuable from a user of faucet-admin point of view:

- [ ] ability to define filters / search (search signup request by e-mail, name, phone, IP)
- [ ] ability to define time/date ranges (i.e. last 3 days, Friday)
- [ ] ability to approve/reject based on filters (approve w/o issues, reject w/ issues, reject telesign score> 900)

Examples:
- Find all signup requests made in Monday-Friday last week, that are using e-mails with `@abusers.nest` and having "issues"<sup>(\*)</sup> and bulk-reject them.
- Find all signups from `@bbc.co.uk` that are without issues "issues"<sup>(\*)</sup> and bulk-accept them.
- Fast-track (find&accept) VIP that you know to have `@therealtrumpet` username (but show enough info to distinguish multiple attempts i.e. one originating from US IP, the other from KP)

**Comment by bonustrack** [comment]
As discussed in the Application Team call, before doing a query builder filter, we will make first a simple search input that query into every user fields. We will also add another input to be able to set a number of results manually.
