### ISSUE TITLE
merge faucet and faucet-admin into one application and one deployment

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet-admin#46]
faucet and faucet-admin share the same database models (as well as some other code that would be useful not to copy-pasta), we should keep them in sync

Options
  * Merge repositories to a monorepo
  * Pull in faucet to faucet-admin as a git submodule
  * Publish a `@steemit/faucet-common` npm package we use from both services

I think the fastest way forward is to have the faucet repo be the source of truth and faucet-admin pulling it in as a submodule, the other options require ops bandwidth which is in short supply right now.

**Comment by jnordberg** [comment]
cc @bonustrack

**Comment by bonustrack** [comment]
I would prefer the option to merge these 2 repos in 1. It's the option that reduce complexity the most.
